# Generated by Django 4.2.9 on 2024-02-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_credentials_device_remove_customer_device_id_and_more'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedwizard',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_wizard', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='personalizedwizard',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_wizard', to='customer.device'),
        ),
        migrations.AddField(
            model_name='personalizedwizard',
            name='template_wizard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_wizard', to='listing.templatewizard'),
        ),
    ]
