# Generated by Django 4.2.9 on 2024-03-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('listing', '0002_personalizedwizardstep_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizedwizardstep',
            name='listing',
        ),
        migrations.AddField(
            model_name='personalizedwizardstep',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_wizard', to='customer.customer'),
        ),
    ]
