# Generated by Django 4.2.9 on 2024-03-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_personalizedwizardstep_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalizedwizardstep',
            old_name='template_wizard',
            new_name='template_wizard_step',
        ),
    ]
