# Generated by Django 4.2.9 on 2024-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_personalizedwizardstep_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='wizard_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
