# Generated by Django 4.2.9 on 2024-03-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_wizard_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewizardstep',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
