# Generated by Django 4.2.9 on 2024-03-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_templatewizardstep_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizedwizardstep',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
