# Generated by Django 4.2.9 on 2024-03-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pbKey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
