# Generated by Django 4.2.9 on 2024-03-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_property_address_number_property_appraised_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mystatemls_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalizedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mystatemls_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_keyword', to='listing.templatekeyword')),
            ],
        ),
    ]
