# Generated by Django 4.2.9 on 2024-03-17 09:15

from django.db import migrations, models
import django.db.models.deletion
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_listing_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to=listing.models.photo_directory_path, verbose_name='Photo')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='listing.listing')),
            ],
        ),
    ]
