# Generated by Django 4.2.9 on 2024-03-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_delete',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
