# Generated by Django 4.2.9 on 2024-03-19 16:09

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_photo_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=255, upload_to=listing.models.photo_directory_path, verbose_name='Photo'),
        ),
    ]
