# Generated by Django 4.2.9 on 2024-03-21 16:22

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0020_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(max_length=255, upload_to=listing.models.photo_directory_path, verbose_name='Photo'),
        ),
    ]
