# Generated by Django 4.2.9 on 2024-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_remove_file_is_delete_file_is_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedwizardstep',
            name='last_index_shown',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalizedwizardstep',
            name='index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
