# Generated by Django 4.2.9 on 2024-03-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_preciselyaccesstoken_expires_in_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciselyaccesstoken',
            name='expires_in_seconds',
        ),
        migrations.AddField(
            model_name='preciselyaccesstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
