# Generated by Django 4.2.9 on 2024-02-14 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_verified_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='device',
            new_name='devices',
        ),
    ]
