# Generated by Django 4.2.9 on 2024-02-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_code', to='customer.customer'),
        ),
    ]
