# Generated by Django 4.2.9 on 2024-02-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_verificationcode_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
