# Generated by Django 4.2.9 on 2024-02-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='verified_phone',
            new_name='verified_phone_or_email',
        ),
    ]
