# Generated by Django 4.2.9 on 2024-02-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_rename_verified_phone_customer_verified_phone_or_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='completed_signup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
